// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Command struct {
	ID           int64
	Name         string
	Description  sql.NullString
	CommandQuery string
	TypeID       int64
}

type CommandFtsIdx struct {
	Name        string
	Description string
}

type CommandType struct {
	ID   int64
	Name string
}
