// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createCommand = `-- name: CreateCommand :one
INSERT INTO command
(name, description, command_query, type_id)
VALUES
(?, ?, ?, ?)
RETURNING id, name, description, command_query, type_id
`

type CreateCommandParams struct {
	Name         string
	Description  sql.NullString
	CommandQuery string
	TypeID       int64
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, createCommand,
		arg.Name,
		arg.Description,
		arg.CommandQuery,
		arg.TypeID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CommandQuery,
		&i.TypeID,
	)
	return i, err
}

const getCommandById = `-- name: GetCommandById :one
SELECT id, name, description, command_query, type_id FROM command WHERE id = ?
`

func (q *Queries) GetCommandById(ctx context.Context, id int64) (Command, error) {
	row := q.db.QueryRowContext(ctx, getCommandById, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CommandQuery,
		&i.TypeID,
	)
	return i, err
}

const updateCommandById = `-- name: UpdateCommandById :one
UPDATE command SET 
    name = ?,
    description = ?,
    command_query = ?
WHERE id = ?
RETURNING id, name, description, command_query, type_id
`

type UpdateCommandByIdParams struct {
	Name         string
	Description  sql.NullString
	CommandQuery string
	ID           int64
}

func (q *Queries) UpdateCommandById(ctx context.Context, arg UpdateCommandByIdParams) (Command, error) {
	row := q.db.QueryRowContext(ctx, updateCommandById,
		arg.Name,
		arg.Description,
		arg.CommandQuery,
		arg.ID,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CommandQuery,
		&i.TypeID,
	)
	return i, err
}
